name: Prisma Cloud Code Security
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Prisma Cloud 
      id: Prisma Cloud
      uses: bridgecrewio/checkov-action@master 
      env:
        PRISMA_API_URL: https://api2.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}